/**
 * Mock data for undergraduate students
 * Used for development and testing without API calls
 */

export interface MockUndergraduate {
  id: string;
  _id: string;
  profilePicture: string | null;
  fullName: string;
  email: string;
  university: string;
  yearOfStudy: number;
  studentIdVerified: boolean;
  phoneNumber: string;
  faculty: string;
  gender: string;
  dateOfBirth: string;
  address: string;
  city: string;
  postalCode: string;
  accountStatus: string;
  verificationStatus: string;
  lastLogin: string;
  bio: string;
  gpa: number;
  skillsAndInterests: string[];
  documentsUploaded: string[];
  joinDate: string;
  verified: boolean;
}

export const mockUndergraduates: MockUndergraduate[] = [
  {
    id: "1",
    _id: "1",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b977?w=100&h=100&fit=crop&crop=face",
    fullName: "Sarah Johnson",
    email: "sarah.johnson@university.edu",
    university: "University of Toronto",
    yearOfStudy: 3,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 123-4567",
    faculty: "Computer Science",
    gender: "Female",
    dateOfBirth: "2002-05-15",
    address: "123 Main Street",
    city: "Toronto",
    postalCode: "M5V 3A8",
    accountStatus: "active",
    verificationStatus: "verified",
    lastLogin: "2024-12-15T10:30:00Z",
    bio: "Passionate computer science student interested in AI and machine learning. Love working on innovative projects and solving complex problems.",
    gpa: 3.8,
    skillsAndInterests: ["JavaScript", "Python", "React", "Machine Learning", "Data Analysis"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf"],
    joinDate: "2023-09-01T00:00:00Z",
    verified: true,
  },
  {
    id: "2",
    _id: "2",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    fullName: "Michael Chen",
    email: "michael.chen@mcgill.ca",
    university: "McGill University",
    yearOfStudy: 2,
    studentIdVerified: false,
    phoneNumber: "+1 (555) 234-5678",
    faculty: "Engineering",
    gender: "Male",
    dateOfBirth: "2003-08-22",
    address: "456 Oak Avenue",
    city: "Montreal",
    postalCode: "H3A 0G4",
    accountStatus: "active",
    verificationStatus: "pending",
    lastLogin: "2024-12-14T15:45:00Z",
    bio: "Engineering student with a focus on sustainable technology and renewable energy systems.",
    gpa: 3.6,
    skillsAndInterests: ["CAD Design", "Renewable Energy", "Mathematics", "Physics", "Project Management"],
    documentsUploaded: ["student_id.jpg"],
    joinDate: "2023-09-15T00:00:00Z",
    verified: false,
  },
  {
    id: "3",
    _id: "3",
    profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    fullName: "Emma Rodriguez",
    email: "emma.rodriguez@ubc.ca",
    university: "University of British Columbia",
    yearOfStudy: 4,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 345-6789",
    faculty: "Business Administration",
    gender: "Female",
    dateOfBirth: "2001-11-08",
    address: "789 Pine Street",
    city: "Vancouver",
    postalCode: "V6T 1Z4",
    accountStatus: "suspended",
    verificationStatus: "verified",
    lastLogin: "2024-12-10T09:20:00Z",
    bio: "Business student specializing in digital marketing and entrepreneurship. Founded a successful student startup.",
    gpa: 3.9,
    skillsAndInterests: ["Digital Marketing", "Entrepreneurship", "Finance", "Leadership", "Strategy"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf", "business_plan.pdf"],
    joinDate: "2023-08-20T00:00:00Z",
    verified: true,
  },
  {
    id: "4",
    _id: "4",
    profilePicture: null,
    fullName: "David Kim",
    email: "david.kim@york.ca",
    university: "York University",
    yearOfStudy: 1,
    studentIdVerified: false,
    phoneNumber: "+1 (555) 456-7890",
    faculty: "Liberal Arts",
    gender: "Male",
    dateOfBirth: "2004-02-28",
    address: "321 Elm Drive",
    city: "Toronto",
    postalCode: "M3J 1P3",
    accountStatus: "active",
    verificationStatus: "rejected",
    lastLogin: "2024-12-13T14:15:00Z",
    bio: "First-year student exploring various academic interests while building foundational knowledge.",
    gpa: 3.2,
    skillsAndInterests: ["Writing", "History", "Philosophy", "Critical Thinking", "Research"],
    documentsUploaded: [],
    joinDate: "2024-09-05T00:00:00Z",
    verified: false,
  },
  {
    id: "5",
    _id: "5",
    profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    fullName: "Alex Thompson",
    email: "alex.thompson@waterloo.ca",
    university: "University of Waterloo",
    yearOfStudy: 3,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 567-8901",
    faculty: "Mathematics",
    gender: "Non-binary",
    dateOfBirth: "2002-09-12",
    address: "654 Maple Lane",
    city: "Waterloo",
    postalCode: "N2L 3G1",
    accountStatus: "active",
    verificationStatus: "verified",
    lastLogin: "2024-12-15T11:00:00Z",
    bio: "Mathematics student with a passion for cryptography and number theory. Active in competitive programming.",
    gpa: 4.0,
    skillsAndInterests: ["Cryptography", "Number Theory", "Competitive Programming", "C++", "Algorithms"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf"],
    joinDate: "2023-09-10T00:00:00Z",
    verified: true,
  },
  {
    id: "6",
    _id: "6",
    profilePicture: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=100&h=100&fit=crop&crop=face",
    fullName: "Jessica Martinez",
    email: "jessica.martinez@queensu.ca",
    university: "Queen's University",
    yearOfStudy: 2,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 678-9012",
    faculty: "Medicine",
    gender: "Female",
    dateOfBirth: "2003-04-07",
    address: "987 Cedar Road",
    city: "Kingston",
    postalCode: "K7L 3N6",
    accountStatus: "inactive",
    verificationStatus: "pending",
    lastLogin: "2024-11-28T08:30:00Z",
    bio: "Pre-med student dedicated to healthcare innovation and community service. Volunteers at local clinics.",
    gpa: 3.7,
    skillsAndInterests: ["Healthcare", "Biology", "Community Service", "Research", "Patient Care"],
    documentsUploaded: ["student_id.jpg"],
    joinDate: "2023-09-12T00:00:00Z",
    verified: false,
  },
  {
    id: "7",
    _id: "7",
    profilePicture: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face",
    fullName: "Ryan O'Connor",
    email: "ryan.oconnor@dal.ca",
    university: "Dalhousie University",
    yearOfStudy: 4,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 789-0123",
    faculty: "Environmental Science",
    gender: "Male",
    dateOfBirth: "2001-12-19",
    address: "147 Birch Avenue",
    city: "Halifax",
    postalCode: "B3H 4R2",
    accountStatus: "active",
    verificationStatus: "verified",
    lastLogin: "2024-12-14T16:20:00Z",
    bio: "Environmental science student focused on climate change research and sustainable development practices.",
    gpa: 3.5,
    skillsAndInterests: ["Climate Research", "Sustainability", "Data Collection", "GIS", "Environmental Policy"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf", "research_paper.pdf"],
    joinDate: "2023-08-28T00:00:00Z",
    verified: true,
  },
  {
    id: "8",
    _id: "8",
    profilePicture: null,
    fullName: "Priya Patel",
    email: "priya.patel@uottawa.ca",
    university: "University of Ottawa",
    yearOfStudy: 1,
    studentIdVerified: false,
    phoneNumber: "+1 (555) 890-1234",
    faculty: "Psychology",
    gender: "Female",
    dateOfBirth: "2004-06-03",
    address: "258 Willow Street",
    city: "Ottawa",
    postalCode: "K1N 6N5",
    accountStatus: "active",
    verificationStatus: "pending",
    lastLogin: "2024-12-15T07:45:00Z",
    bio: "First-year psychology student interested in cognitive behavioral therapy and mental health advocacy.",
    gpa: 3.4,
    skillsAndInterests: ["Psychology", "Mental Health", "Counseling", "Research Methods", "Statistics"],
    documentsUploaded: ["student_id.jpg"],
    joinDate: "2024-09-03T00:00:00Z",
    verified: false,
  },
  {
    id: "9",
    _id: "9",
    profilePicture: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face",
    fullName: "James Wilson",
    email: "james.wilson@mun.ca",
    university: "Memorial University",
    yearOfStudy: 5,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 901-2345",
    faculty: "Marine Biology",
    gender: "Male",
    dateOfBirth: "2000-10-14",
    address: "369 Spruce Hill",
    city: "St. John's",
    postalCode: "A1C 5S7",
    accountStatus: "active",
    verificationStatus: "verified",
    lastLogin: "2024-12-15T13:10:00Z",
    bio: "Graduate student in marine biology researching ocean conservation and marine ecosystem dynamics.",
    gpa: 3.8,
    skillsAndInterests: ["Marine Biology", "Ocean Conservation", "Scuba Diving", "Research", "Data Analysis"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf", "thesis_proposal.pdf"],
    joinDate: "2023-08-15T00:00:00Z",
    verified: true,
  },
  {
    id: "10",
    _id: "10",
    profilePicture: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face",
    fullName: "Lisa Zhang",
    email: "lisa.zhang@sfu.ca",
    university: "Simon Fraser University",
    yearOfStudy: 2,
    studentIdVerified: true,
    phoneNumber: "+1 (555) 012-3456",
    faculty: "Arts and Social Sciences",
    gender: "Female",
    dateOfBirth: "2003-01-25",
    address: "741 Fir Street",
    city: "Burnaby",
    postalCode: "V5A 1V2",
    accountStatus: "active",
    verificationStatus: "verified",
    lastLogin: "2024-12-14T12:25:00Z",
    bio: "Sociology student passionate about social justice, community organizing, and cultural diversity research.",
    gpa: 3.6,
    skillsAndInterests: ["Sociology", "Social Justice", "Community Organizing", "Cultural Studies", "Public Speaking"],
    documentsUploaded: ["student_id.jpg", "transcript.pdf"],
    joinDate: "2023-09-08T00:00:00Z",
    verified: true,
  },
];

// Mock API functions
export const mockUndergraduatesApi = {
  getAll: () => Promise.resolve(mockUndergraduates),
  verify: (id: string) => {
    console.log(`Mock: Verifying undergraduate with ID: ${id}`);
    return Promise.resolve({ success: true, id });
  },
  suspend: (id: string) => {
    console.log(`Mock: Suspending undergraduate with ID: ${id}`);
    return Promise.resolve({ success: true, id });
  },
  activate: (id: string) => {
    console.log(`Mock: Activating undergraduate with ID: ${id}`);
    return Promise.resolve({ success: true, id });
  },
};
